spring:
    main:
        banner-mode: #off
    banner:
        location: classpath:banner.txt
    security:
        user:
            name: admin
            password: admin
            roles: ACTUATOR_ADMIN
    # DB configuration
    datasource:
        mysql:
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://localhost:3306/multi_datasource_db?createDatabaseIfNotExist=true
            username: root
            password: root
        postgresql:
            driver-class-name: org.postgresql.Driver
            url: jdbc:postgresql://localhost:5432/multi_datasource_db?currentSchema=dev
            username: postgres
            password: root

    jpa:
        generate-ddl: true
        open-in-view: false
        show-sql: true
        hibernate:
            ddl-auto: create

server:
    port: 8080

audit:
    connector:
        url: http://localhost:8085/audit
        username: audit
        password: audit

logging:
    level:
        root: INFO
        com:
            sid: INFO